#!/bin/bash
#SBATCH --cpus-per-task 8           # 1 core(CPU)
#SBATCH --nodes=1                # Use 1 node
#SBATCH --job-name=admixture
#SBATCH --mem=8G                 # Default memory per CPU is 3GB
#SBATCH --output=admixture.%A_%a.txt 
#SBATCH --constraint=avx2

module load VCFtools
module load BCFtools
module load tabixpp/1.1.0-GCC-10.2.0
module load SAMtools
module load PLINK/1.9b_6.17-x86_64

#Notes :
#Input = a merged file containing the 4 populations and already filtered for depth, low quality variants and missingness
#For structure analysis : need to filter MAF, HW and Linkage desequilibrum.

#Directories for input and output 
VCF=/mnt/SCRATCH/pabu/Soft_filtering/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz
OUT=/net/fs-2/scale/OrionStore/Scratch/pabu/PCA_admixture/admixture

#create variants ids for LD pruning :
#bcftools annotate --set-id '%CHROM\_%POS\_%REF\_%ALT' -c ID $VCF | bgzip > ${OUT}/admixture_input_ids.vcf.gz
#tabix -p vcf ${OUT}/admixture_input_ids.vcf.gz

#remove the ssa0 and ssa in chromosome name because admixture does not recognize only numeric values
zcat $VCF |sed 's/ssa0//g' |sed 's/ssa//g'| pigz -p 4 > ${OUT}/admixture_input_ids_renamed.vcf.gz

#LD prunning + MAF cutting off

plink --vcf ${OUT}/admixture_input_ids_renamed.vcf.gz --hwe 0.0001 --maf 0.05 --indep-pairwise 50 10 0.5 --out ${OUT}/filtering --recode vcf bgz --double-id --aec --threads 8 --dog
tabix -p vcf ${OUT}/filtering.vcf.gz
plink --vcf ${OUT}/filtering.vcf.gz --exclude ${OUT}/filtering.prune.out --out ${OUT}/input_admixture_final --recode vcf bgz --double-id --aec --threads 8 --dog
tabix -p vcf ${OUT}/input_admixture_final.vcf.gz

#Convert vcf file to plink format for admixture input.
plink --vcf ${OUT}/input_admixture_final.vcf.gz --make-bed --out ${OUT}/input_admixture --aec --dog --threads 8 --double-id

#run admixture
for K in {1..10} ; do
singularity exec /cvmfs/singularity.galaxyproject.org/all/admixture:1.3.0--0 admixture --cv=10 ${OUT}/input_admixture.bed $K > ${OUT}/admixture_output.$K.log
done
