#!/bin/bash
#SBATCH --cpus-per-task 8           # 1 core(CPU)
#SBATCH --nodes=1                # Use 1 node
#SBATCH --job-name=admixture
#SBATCH --mem=8G                 # Default memory per CPU is 3GB
#SBATCH --output=admixture.%A_%a.txt 
#SBATCH --constraint=avx2


VCF=/net/fs-2/scale/OrionStore/Scratch/pabu/Pass_filtered_datasets/4pops_celian_merged_ids.vcf.gz
OUT=/net/fs-2/scale/OrionStore/Scratch/pabu/PCA_admixture/admixture/celian_files

module load PLINK/1.9b_6.17-x86_64
module load VCFtools
module load tabixpp/1.1.0-GCC-10.2.0
module load SAMtools

zcat $VCF |sed 's/ssa0//g' |sed 's/ssa//g'| pigz -p 4 > ${OUT}/4_pops_renamed.vcf.gz

plink --vcf ${OUT}/4_pops_renamed.vcf.gz --geno 0.1 --maf 0.05 --indep-pairwise 50 10 0.1 --out ${OUT}/filtering --recode vcf bgz --double-id --aec --threads 8 --dog
tabix -p vcf ${OUT}/filtering.vcf.gz
plink --vcf ${OUT}/filtering.vcf.gz --exclude ${OUT}/filtering.prune.out --out ${OUT}/4_pops_merged_filtered_admixture --recode vcf bgz --double-id --aec --threads 8 --dog
tabix -p vcf ${OUT}/4_pops_merged_filtered_admixture.vcf.gz

plink --vcf ${OUT}/4_pops_merged_filtered_admixture.vcf.gz --make-bed --out ${OUT}/input_admixture --aec --dog --threads 8 --double-id

#plink --bfile ${OUT}/filtering --exclude ${OUT}/filtering.prune.out --make-bed --out ${OUT}/input_admixture --aec --dog --threads 8

#run admixture
for K in {1..10} ; do
singularity exec /cvmfs/singularity.galaxyproject.org/all/admixture:1.3.0--0 admixture --cv=10 ${OUT}/input_admixture.bed $K > ${OUT}/admixture_output.$K.log
done
