#!/bin/bash
#SBATCH --ntasks=1         # 1 core(CPU)
#SBATCH --nodes=1
#SBATCH --job-name=Fst_stats
#SBATCH --mem=8G

###WARNING###
#do the PASS_filtering before for FST calculation + depth, low quality variants and missingness filtering

#Directories
OUT=/net/fs-2/scale/OrionStore/Scratch/pabu/Fst

module load BCFtools 
module load SAMtools
module load tabixpp/1.1.0-GCC-10.2.0
module load VCFtools

#demerge the file containing the 4 pops, two by two to create Fst input (farmed + wild from the same region)

bcftools view /mnt/SCRATCH/pabu/Soft_filtering/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz -S ${OUT}/euro_samples.txt -O z -o ${OUT}/fst_input_euro.vcf.gz
tabix -p vcf ${OUT}/fst_input_euro.vcf.gz

###Wild Norway - MOWI
vcftools --gzvcf ${OUT}/fst_input_euro.vcf.gz --weir-fst-pop ${OUT}/farmed_euro_samples.txt --weir-fst-pop ${OUT}/wild_euro_samples.txt --fst-window-size 5000 --out ${OUT}/Fst_stats_Euro #fst-command

###Wild NA - Farmed NA
bcftools view /mnt/SCRATCH/pabu/Soft_filtering/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz -S ${OUT}/american_samples.txt -O z -o ${OUT}/fst_input_american.vcf.gz
tabix -p vcf ${OUT}/fst_input_american.vcf.gz
vcftools --gzvcf ${OUT}/fst_input_american.vcf.gz --weir-fst-pop ${OUT}/farmed_american_samples.txt --weir-fst-pop ${OUT}/wild_american_samples.txt --fst-window-size 5000 --out ${OUT}/Fst_stats_american #fst-command
