#!/bin/bash
#SBATCH --cpus-per-task 8           # 1 core(CPU)
#SBATCH --nodes=1                # Use 1 node
#SBATCH --job-name=pca
#SBATCH --mem=8G                 # Default memory per CPU is 3GB
#SBATCH --output=pca.%A_%a.txt 
#SBATCH --constraint=avx2

module load VCFtools
module load BCFtools
module load tabixpp/1.1.0-GCC-10.2.0
module load SAMtools
module load PLINK/1.9b_6.17-x86_64

#Notes :
#Input = a merged file containing the 4 populations and already filtered for depth, low quality variants and missingness
#For structure analysis : need to filter MAF, HW and Linkage desequilibrum.

#Directories for input and output 
VCF=/mnt/SCRATCH/pabu/Soft_filtering/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz
OUT=/net/fs-2/scale/OrionStore/Scratch/pabu/PCA_admixture/PCA

#create variants ids for LD pruning :

bcftools annotate --set-id '%CHROM\_%POS\_%REF\_%ALT' -c ID $VCF | bgzip > ${OUT}/PCA_input_ids.vcf.gz
tabix -p vcf ${OUT}/PCA_input_ids.vcf.gz

#LD prunning + MAF cutting off

plink --vcf ${OUT}/PCA_input_ids.vcf.gz --hwe 0.001 --maf 0.05 --indep-pairwise 50 10 0.5 --out ${OUT}/PCA_filtering --recode vcf bgz --double-id --aec --threads 8 --dog
tabix -p vcf ${OUT}/PCA_filtering.vcf.gz
plink --vcf ${OUT}/PCA_filtering.vcf.gz --exclude ${OUT}/PCA_filtering.prune.out --out ${OUT}/PCA_input_final --recode vcf bgz --aec --double-id --threads 8 --dog
tabix -p vcf ${OUT}/PCA_input_final.vcf.gz

#Run the PCA
plink --vcf ${OUT}/PCA_input_final.vcf.gz --pca 10 --out ${OUT}/pca_4pops --aec --threads 8 --dog --double-id

#extract the right order of samples for the plot on R
bcftools query -l ${OUT}/PCA_input_final.vcf.gz > ${OUT}/samples_pca_list.txt

