#!/bin/bash
#SBATCH --ntasks=1         # 1 core(CPU)
#SBATCH --nodes=1
#SBATCH --job-name=data_filtering.job
#SBATCH --mem=8G
#SBATCH --output=filtering_job_output.%j.txt
#SBATCH --constraint=avx2

#This pipeline is used to add filters, different from those in the GATK genotype calling pipeline. 
#The filtering is done on a merged file to keep only common markers with good quality.

#!/bin/bash
#SBATCH --ntasks=1         # 1 core(CPU)
#SBATCH --nodes=1
#SBATCH --job-name=data_filtering.job
#SBATCH --mem=20G
#SBATCH --output=filtering_job_output.%j.txt
#SBATCH --constraint=avx2

module load VCFtools
module load tabixpp/1.1.0-GCC-10.2.0
module load SAMtools
module load BCFtools

#merge the 4 populations (raw snps previously extracted)

bcftools merge /mnt/SCRATCH/pabu/Raw_datasets/Farmed_european_ids.vcf.gz /mnt/SCRATCH/pabu/Raw_datasets/Wild_european_ids.vcf.gz /mnt/SCRATCH/pabu/Raw_datasets/Farmed_NAmerica_ids.vcf.gz /mnt/SCRATCH/pabu/Raw_datasets/Wild_NAmerica_ids.vcf.gz | bgzip > /mnt/SCRATCH/pabu/Soft_filtering/4pops_merged.vcf.gz
tabix -p vcf /mnt/SCRATCH/pabu/Soft_filtering/4pops_merged.vcf.gz

#add variants ids : facultative
#bcftools annotate --set-id '%CHROM\_%POS\_%REF\_%ALT' -c ID /mnt/SCRATCH/pabu/Pass_filtered_datasets/4pops_celian_merged.vcf.gz | bgzip > /mnt/SCRATCH/pabu/Pass_filtered_datasets/4pops_celian_merged_ids.vcf.gz
#tabix -p vcf /mnt/SCRATCH/pabu/Pass_filtered_datasets/4pops_merged_ids.vcf.gz

#Pass filtering : to keep ony the variant that PASS the GATK filter tag from mapping and genotype calling pipeline

WD=/mnt/SCRATCH/pabu/Soft_filtering/4pops_merged.vcf.gz
OUT=/mnt/SCRATCH/pabu/Soft_filtering

bcftools view -H $WD | awk '{if(index($7,"PASS")){print $0}}' > ${OUT}/PASS_filtered.vcf #view and print only the table+remove all the variants which are not PASS
bcftools view -h $WD > ${OUT}/header.vcf #view and print only the header
cat ${OUT}/header.vcf ${OUT}/PASS_filtered.vcf > ${OUT}/4pops_merged_PASS.vcf #colle les deux
bgzip ${OUT}/4pops_merged_PASS.vcf #compress
tabix -p vcf ${OUT}/4pops_merged_PASS.vcf.gz #index

#remove the weird variants with 3 alleles even I extracted the bi-allelic variants, some of them are still in the file

bcftools view -H ${OUT}/4pops_merged_PASS.vcf.gz | awk '$5 !~/,/ {print $0}' > ${OUT}/4pops_merged_PASS_trimmed.vcf
bcftools view -h ${OUT}/4pops_merged_PASS.vcf.gz > ${OUT}/header_trimmed.vcf
cat ${OUT}/header_trimmed.vcf ${OUT}/4pops_merged_PASS_trimmed.vcf > ${OUT}/4pops_merged_PASS_final.vcf
bgzip ${OUT}/4pops_merged_PASS_final.vcf
tabix -p vcf ${OUT}/4pops_merged_PASS_final.vcf.gz

#Filtering : depth, low quality variants, missingness

MIN_DEPTH=4
MAX_DEPTH=30
GQ=10
MISS=0.9

vcftools --gzvcf ${OUT}/4pops_merged_PASS_final.vcf.gz --min-meanDP $MIN_DEPTH --max-meanDP $MAX_DEPTH --minDP $MIN_DEPTH --maxDP $MAX_DEPTH --minGQ $GQ --max-missing $MISS --remove-filtered-all --recode --out  ${OUT}/4pops_merged_filtered_depth_lqual_miss
bgzip ${OUT}/4pops_merged_filtered_depth_lqual_miss.recode.vcf
tabix -p vcf ${OUT}/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz #index

#demerge the files 

bcftools view ${OUT}/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz -S ${OUT}/FE_samples.txt -O z -o ${OUT}/farmed_european.vcf.gz
tabix -p vcf ${OUT}/farmed_european.vcf.gz

bcftools view ${OUT}/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz -S ${OUT}/WE_samples.txt -O z -o ${OUT}/wild_european.vcf.gz
tabix -p vcf ${OUT}/wild_european.vcf.gz

bcftools view ${OUT}/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz -S ${OUT}/FA_samples.txt -O z -o ${OUT}/farmed_american.vcf.gz
tabix -p vcf ${OUT}/farmed_american.vcf.gz

bcftools view ${OUT}/4pops_merged_filtered_depth_lqual_miss.recode.vcf.gz -S ${OUT}/WA_samples.txt -O z -o ${OUT}/wild_american.vcf.gz
tabix -p vcf ${OUT}/wild_american.vcf.gz

