#!/bin/bash
#SBATCH --ntasks=1         # 1 core(CPU)
#SBATCH --nodes=1
#SBATCH --job-name=data_filtering.job
#SBATCH --mem=8G
#SBATCH --output=filtering_job_output.%j.txt
#SBATCH --constraint=avx2

#This pipeline is used to add filters, different from those in the GATK genotype calling pipeline. 
#This filtering is useful before phasing and can be adapted according to the analyses you want to do. 
#We have seen that FST and Tajima do not require soft filtering. 
#But haplotype-based analyses that require phased data need to be filtered in depth. 
#The filters were chosen according to the results obtained on the R data quality script. (see the R pipeline data quality)

#Europe
#My directories for input and outputs
VCF1=/mnt/SCRATCH/cedi/phDSalmon/sv_detection/filtervcf/Only_SNP_Farmed_Europe_filtered.recode.vcf.gz
VCF2=/mnt/SCRATCH/cedi/phDSalmon/sv_detection/filtervcf/Only_SNP_Wild_Europe_filtered.recode.vcf.gz
OUT=/net/fs-2/scale/OrionStore/Scratch/pabu/Soft_filtering/celian_files

#filters according to R results (can be adapted according to datasets and data quality)
MIN_DEPTH1=8.5 #farmed
MIN_DEPTH2=6 #wild
MAX_DEPTH=30 #all pop
MAF=0.01

#Load the tools
module load VCFtools
module load tabixpp/1.1.0-GCC-10.2.0
module load SAMtools

#Perform filteringwith VCFtools because Plink change the vcf format.
vcftools --gzvcf $VCF1 --maf $MAF --min-meanDP $MIN_DEPTH1 --max-meanDP $MAX_DEPTH --minDP $MIN_DEPTH1 --maxDP $MAX_DEPTH --recode --out ${OUT}/farmed_european_filtered
bgzip ${OUT}/farmed_european_filtered.recode.vcf #zip
tabix -p vcf ${OUT}/farmed_european_filtered.recode.vcf.gz #index

vcftools --gzvcf $VCF2 --maf $MAF --min-meanDP $MIN_DEPTH2 --max-meanDP $MAX_DEPTH --minDP $MIN_DEPTH2 --maxDP $MAX_DEPTH --recode --out ${OUT}/wild_european_filtered
bgzip ${OUT}/wild_european_filtered.recode.vcf #zip
tabix -p vcf ${OUT}/wild_european_filtered.recode.vcf.gz #index

#other option of filtering with plink : 
#module load PLINK/2.00a2.3_x86_64 #also possible with plink 1.9 because it is still unphased data at this step.
#plink2 --vcf ${OUT}/Wild_european_depth.recode.vcf --geno 0.1 --maf 0.05 --out ${OUT}/Wild_Norway_Pass_filtered --recode vcf bgz id-paste=iid --aec --threads 8 --dog

###Filtering-AMERICAN###
VCF3=/mnt/SCRATCH/cedi/phDSalmon/sv_detection/filtervcf/Only_SNP_Farmed_American_filtered.recode.vcf.gz
VCF4=/mnt/SCRATCH/cedi/phDSalmon/sv_detection/filtervcf/Only_SNP_Wild_American_filtered.recode.vcf.gz

#Filters for american population
MIN_DEPTH3=12 #farmed
MIN_DEPTH4=5 #wild

vcftools --gzvcf $VCF3 --maf $MAF --min-meanDP $MIN_DEPTH3 --max-meanDP $MAX_DEPTH --minDP $MIN_DEPTH3 --maxDP $MAX_DEPTH --recode --out ${OUT}/farmed_american_filtered
bgzip ${OUT}/farmed_american_filtered.recode.vcf
tabix -p vcf ${OUT}/farmed_american_filtered.recode.vcf.gz #index

vcftools --gzvcf $VCF4 --maf $MAF --min-meanDP $MIN_DEPTH4 --max-meanDP $MAX_DEPTH --minDP $MIN_DEPTH4 --maxDP $MAX_DEPTH --recode --out ${OUT}/wild_american_filtered
bgzip ${OUT}/wild_american_filtered.recode.vcf
tabix -p vcf ${OUT}/wild_american_filtered.recode.vcf.gz #index
