#!/bin/bash
#SBATCH --ntasks=1               # 1 core(CPU)
#SBATCH --nodes=1                # Use 1 node
#SBATCH --job-name=tajima
#SBATCH --mem=8G                 # Default memory per CPU is 3GB
#SBATCH --mail-user=pauline.marie.buso@nmbu.no # Email me when job is done.
#SBATCH --mail-type=END
#SBATCH --output=tajima.out

module load HTSlib
module load VCFtools

#these inputs are from a merged file already filtered for depth, low quality variants, and missingness
VCF1=/mnt/SCRATCH/pabu/Soft_filtering/farmed_european.vcf.gz
VCF2=/mnt/SCRATCH/pabu/Soft_filtering/farmed_american.vcf.gz

OUT=/net/fs-2/scale/OrionStore/Scratch/pabu/Tajima

vcftools --gzvcf $VCF1 --out ${OUT}/tajima_farmed_euro --TajimaD 20000
vcftools --gzvcf $VCF1 --window-pi 20000 --window-pi-step 5000 --out ${OUT}/farmed_euro_nucl_div_SNPs

vcftools --gzvcf $VCF2 --out ${OUT}/tajima_farmed_american --TajimaD 20000
vcftools --gzvcf $VCF2 --window-pi 20000 --window-pi-step 5000 --out ${OUT}/farmed_american_nucl_div_SNPs

