#!/bin/bash
#SBATCH --ntasks=1         # 1 core(CPU)
#SBATCH --nodes=1
#SBATCH --job-name=data_filtering.job
#SBATCH --mem=50G
#SBATCH --output=call_snp_filtereing_merging.%j.txt
#SBATCH --constraint=avx2

module load BCFtools
module load tabixpp/1.1.0-GCC-10.2.0

#Directories 
WD=/net/fs-2/scale/OrionStore/Projects/MSLab/Pauline #folder with the raw data (SNPs, Indels, SV)
OUT=/net/fs-2/scale/OrionStore/Scratch/pabu/Raw_datasets

#Take out only the SNPs from files with SNP + indels.
#Farmed-European samples
bcftools view -M 2 -m 2 -v snps /mnt/project/MSLab/Shared_Data/Synchrosmolt_parents/renamed_MOWI_wgs_parents.vcf.gz -Oz -o ${OUT}/Farmed_european.vcf.gz --threads 10
tabix -p vcf ${OUT}/Farmed_european.vcf.gz

#Wild-European samples
bcftools view -M 2 -m 2 -v snps ${WD}/Wild_Norway.vcf.gz -Oz -o ${OUT}/Wild_european.vcf.gz --threads 16
tabix -p vcf ${OUT}/Wild_european.vcf.gz

#Wild-North-American samples
bcftools view -M 2 -m 2 -v snps ${WD}/Wild_NAmerica.vcf.gz -Oz -o ${OUT}/Wild_NAmerica.vcf.gz --threads 16
tabix -p vcf ${OUT}/Wild_NAmerica.vcf.gz

#Farmed_American samples
bcftools view -M 2 -m 2 -v snps ${WD}/Farmed_NAmerica.vcf.gz -Oz -o ${OUT}/Farmed_NAmerica.vcf.gz --threads 16
tabix -p vcf ${OUT}/Farmed_NAmerica.vcf.gz
